owner: forgeVTT 
repo: upptime 
sites:
  - name: Forge VTT API Server
    url: https://ping.forge-vtt.com/api/ping
  - name: Forge VTT EU 
    url: https://ping.eu.forge-vtt.com/api/ping
  - name: Forge VTT Australia
    url: https://ping.au.forge-vtt.com/api/ping
  - name: Forge VTT Asia
    url: https://ping.as.forge-vtt.com/api/ping

status-website:
  baseUrl: /upptime/
  logoUrl: https://forge-vtt.com/images/the-forge-logo-48x48.png
  name: "Forge VTT Global Uptime Dashboard"
  introTitle: "**Forge VTT** Global Uptime Dashboard Monitoring"
  introMessage: "**The Forge** is a no-hassle roleplaying gaming platform — a hosting service and so much more — powered by Foundry Virtual Tabletop and our unique integration technologies. [**Fight Goblins, Not Servers!**]"
  navbar:
    - title: Status
      href: /
    - title: Contact
      href: https://forge-vtt.com/contact
