owner: forgeVTT 
repo: upptime
user-agent: upptime github monitor

#status-page:
#  theme: "ocean"
assignees:
  - ThatGuyAtGithub

sites:
  - name: The Forge VTT API North America 
    url: https://ping.forge-vtt.com/api/ping
  - name: The Forge VTT API Europe
    url: https://ping.eu.forge-vtt.com/api/ping
  - name: The Forge VTT API Asia
    url: https://ping.as.forge-vtt.com/api/ping
  - name: The Forge VTT API Australia
    url: https://ping.au.forge-vtt.com/api/ping

status-website:
  cname: up.forge-vtt.com
  baseUrl: /
  logoUrl: https://forge-vtt.com/images/the-forge-logo-48x48.png
  name: "The Forge VTT"
  introTitle: "**The Forge VTT** Global Uptime Dashboard"
  introMessage: "**The Forge** is a no-hassle roleplaying gaming platform — a hosting service and so much more — powered by Foundry Virtual Tabletop and our unique integration technologies. [**Fight Goblins, Not Servers!**]"
  navbar:
    - title: Contact
      href: https://forge-vtt.com/contact
